import SideBar from "./components/SideBar"
function App() {
  return (
    <div className="bg-slate-200 min-h-screen">
      <SideBar />
      <h1 className="px-10 pb-10 pt-20 text-3xl font-bold">Lorem Ipsum</h1>
      <p className="md:columns-2 lg:columns-3 px-10 pb-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nec risus tellus. Praesent quis rutrum felis. Vivamus venenatis dapibus risus, vel convallis enim varius vel. In dictum lacus et placerat laoreet. Etiam rutrum lacus diam, sit amet scelerisque dui commodo sit amet. Nam tristique, mauris sit amet ullamcorper pulvinar, nunc arcu pellentesque lacus, a accumsan libero dui nec erat. Integer et ultricies tellus. Duis sagittis vitae quam eget tempor. Donec elementum sodales tincidunt. Phasellus ut orci id erat condimentum efficitur sed eu tortor. Vivamus sollicitudin tortor et augue pulvinar consectetur. Etiam viverra odio eget ex viverra, eget elementum magna blandit. Praesent vel mi tincidunt, iaculis mauris quis, aliquet arcu. Proin malesuada, ex nec pellentesque consectetur, est metus congue odio, bibendum tempus metus velit id orci. Fusce gravida nisi quis dui interdum iaculis. Morbi dignissim, ligula in vestibulum eleifend, tortor lectus interdum tellus, posuere porttitor metus velit eu elit.

        Nam auctor sodales molestie. Curabitur non ornare orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut eleifend eleifend est, et rutrum lacus vehicula at. Vivamus ac vulputate sapien. Etiam velit nibh, feugiat sit amet luctus ut, hendrerit quis purus. Phasellus ornare urna et turpis aliquam, eu pretium sem rhoncus. Phasellus nec scelerisque nibh. Maecenas gravida erat vitae lectus dignissim, ac facilisis nisi blandit. Phasellus mollis et tellus quis semper. In sit amet eros mauris. Aliquam ut ex orci. Praesent venenatis iaculis neque non molestie.

        Ut sagittis fermentum consequat. Ut efficitur tellus ac nibh tempor, nec suscipit erat cursus. Duis aliquet nulla ac magna sodales iaculis. Vestibulum eu imperdiet quam. Vestibulum interdum augue sed magna eleifend, in gravida ligula feugiat. Vestibulum lobortis a neque quis blandit. Donec suscipit et quam at egestas. Aliquam id molestie leo. Donec faucibus, augue nec placerat laoreet, metus sapien tristique elit, ac lobortis purus metus id elit. Maecenas non gravida massa. Donec vel nulla vitae magna luctus maximus. Suspendisse potenti. Nunc aliquam in nisl eu pharetra. Praesent elementum nibh sit amet condimentum porta. Quisque ac egestas quam.

        Nullam convallis eget turpis et tincidunt. Donec lobortis ornare ornare. Aenean sagittis, tortor at interdum placerat, urna urna suscipit mi, et porttitor quam orci in lorem. Vivamus dignissim eleifend nisi, vitae gravida orci porttitor quis. Proin feugiat ipsum at lectus eleifend varius. Nam et neque in enim cursus blandit eu ac nisi. Sed consequat nec mauris eget lobortis. Pellentesque convallis risus et dictum aliquet. Quisque nisl felis, malesuada ac tempor eu, porttitor eget tellus. Integer ultricies mollis lorem sed porttitor. Suspendisse varius convallis ullamcorper.

        Vivamus at neque vitae leo congue consequat. Fusce volutpat risus at urna pharetra ultricies. Aliquam velit ipsum, pellentesque a diam nec, fringilla tempor orci. Phasellus nec augue non urna suscipit facilisis ultrices vel magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam tristique magna nec mi pretium aliquet. Donec dolor arcu, eleifend a euismod vel, iaculis a dolor. Aliquam vel purus non ex ultricies tempus id in orci. Donec feugiat nibh odio, eget cursus lacus tincidunt ut.

        Donec sed tempor ex. Sed scelerisque tellus sit amet erat pharetra, sit amet varius ipsum vulputate. Nam malesuada, turpis et bibendum vestibulum, arcu tortor imperdiet nibh, nec cursus felis lorem gravida purus. In gravida, mauris ac ultricies vulputate, tellus felis auctor est, eget molestie felis ante quis est. Donec ultricies feugiat lacus, eget ullamcorper sem pretium non. Integer non dignissim urna. Suspendisse dapibus luctus elit. Phasellus non quam ac justo suscipit consequat sit amet volutpat nisl. Praesent viverra tortor vel accumsan ultrices. Nulla auctor placerat malesuada. Nam venenatis, dolor vitae mollis posuere, risus turpis auctor leo, in lacinia velit urna a lectus. Fusce non mattis massa. Fusce ac porta tortor. Praesent ullamcorper et sem et tristique.

        Quisque interdum leo a urna aliquet pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc mollis urna ligula, id scelerisque tellus congue eget. Cras vel odio vestibulum, finibus odio sit amet, vehicula quam. Praesent pharetra elit sit amet malesuada egestas. Duis porta porttitor mauris, et ullamcorper purus dapibus non. Donec congue felis ut eros euismod pulvinar. Sed vitae est vitae magna lobortis condimentum. Nam ac turpis dignissim, consequat lorem quis, sagittis mi. Nam vehicula tortor sem, vel aliquam odio lobortis sed. Sed vestibulum aliquam dui eget congue.

        Mauris efficitur tristique bibendum. Nullam eleifend odio libero, ac egestas est molestie at. Sed molestie lorem nulla, id vulputate elit blandit sed. Maecenas id egestas lacus. Mauris pellentesque augue quis nisi venenatis, quis bibendum ex ornare. Aenean mattis, leo quis mattis mattis, ligula erat tincidunt justo, et feugiat purus purus ut nisi. Vivamus bibendum efficitur turpis aliquet sodales. Nulla venenatis pellentesque lorem in pellentesque. Etiam quis felis augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam blandit arcu et eros consequat, nec egestas ligula rutrum. Morbi sit amet lacus sit amet ipsum iaculis aliquam nec eu turpis. Etiam et lacinia elit. Vivamus eget pellentesque metus. Curabitur dictum tincidunt velit, quis posuere massa interdum ac. Sed massa odio, sagittis ut tempus sed, placerat et neque.

        Praesent hendrerit ligula a lectus sagittis sagittis. Praesent cursus accumsan odio a placerat. Phasellus dignissim urna gravida neque iaculis vulputate. Duis dapibus dignissim semper. Phasellus sed leo enim. Nulla faucibus vitae eros sed dictum. Suspendisse at elementum sem, quis auctor purus. Aenean pellentesque ante nec dolor consectetur, non porttitor ligula maximus. In mollis arcu turpis, a interdum nulla ullamcorper ornare. Maecenas scelerisque leo sit amet gravida auctor. Ut at egestas quam. Mauris egestas nunc eget est tincidunt facilisis.

        Morbi aliquam pharetra ultricies. Ut eget lectus sed quam sollicitudin congue. Praesent erat tortor, commodo egestas viverra a, sagittis sit amet ex. Aenean ex tellus, ultrices eget ornare sit amet, ultricies et nisi. Cras nec blandit enim. Mauris quis tortor mi. Ut hendrerit massa eget metus tincidunt, vel malesuada elit pellentesque. Duis in est ut magna congue dictum. Fusce dignissim fringilla placerat. Nam quis luctus dui. Sed tempus nunc vitae imperdiet fringilla. Quisque malesuada mauris sit amet justo sodales, a fermentum tellus varius. Nunc gravida nulla eget nisi dignissim, lobortis fringilla diam mollis. In tellus sem, tincidunt hendrerit lorem a, euismod iaculis neque. Donec congue erat ac arcu commodo dapibus eu at odio. Praesent sit amet diam eget elit dictum imperdiet.</p>
    </div>
  );
}
export default App;
